export const GAME_CONFIG = {
  CARDS_BEFORE_SPEED_ROUND: 3,
  CARDS_BEFORE_BOSS_ROUND: 3,

  SPEED_ROUND: {
    DURATION_SECONDS: 30,
    XP_PER_CORRECT: 10,
    MAX_QUESTIONS: 20,
  },

  BOSS_ROUND: {
    XP_PER_CORRECT: 5,
    XP_PENALTY_PER_WRONG: 2,
    COMBO_THRESHOLD: 3,
    COMBO_MULTIPLIER: 2,
  },

  XP: {
    CARD_UNDERSTOOD: 5,
    CARD_ALREADY_KNOWN: 2,
    STREAK_BONUS_PER_DAY: 10,
  },

  PREFETCH: {
    NEXT_BATCH_SIZE: 10,
    TRIGGER_AT_REMAINING: 3,
  },

  SWIPE: {
    THRESHOLD: 120,
    VELOCITY_THRESHOLD: 800,
  },

  LEVELS: {
    XP_PER_LEVEL: 500,
  },
} as const;

export type GameConfig = typeof GAME_CONFIG;
