import { StyleSheet } from 'react-native';
import { colors, spacing } from '../../../../app/theme';

export const styles = StyleSheet.create({
  root: {
    margin: spacing.md,
    marginBottom: 0,
    gap: spacing.sm,
  },

  // ── Title card ─────────────────────────────────────────────────────
  titleCard: {
    backgroundColor: colors.bgElevated,
    borderWidth: 3,
    borderColor: colors.border,
    borderRadius: 8,
    padding: spacing.lg,
    gap: spacing.xs,
    shadowColor: colors.shadow,
    shadowOffset: { width: 5, height: 5 },
    shadowRadius: 0,
    shadowOpacity: 1,
    elevation: 5,
    overflow: 'hidden',
    position: 'relative',
  },
  titleCardDec: {
    position: 'absolute',
    width: 60,
    height: 60,
    borderRadius: 4,
    backgroundColor: colors.primaryLight,
    borderWidth: 2,
    borderColor: colors.borderLight,
    top: -20,
    right: -16,
    transform: [{ rotate: '12deg' }],
  },
  nowPlaying: {
    fontSize: 8,
    fontWeight: '900',
    color: colors.primary,
    letterSpacing: 2,
    textTransform: 'uppercase',
    zIndex: 1,
  },
  videoTitle: {
    fontSize: 17,
    fontWeight: '900',
    color: colors.text,
    lineHeight: 23,
    zIndex: 1,
  },
  creatorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    marginTop: 2,
    zIndex: 1,
  },
  creatorDot: {
    width: 5,
    height: 5,
    borderRadius: 2,
    backgroundColor: colors.primary,
  },
  creator: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.textMuted,
  },

  // ── Key insight card ───────────────────────────────────────────────
  insightCard: {
    borderWidth: 3,
    borderColor: colors.border,
    borderRadius: 8,
    backgroundColor: colors.primary,
    padding: spacing.lg,
    shadowColor: colors.shadow,
    shadowOffset: { width: 5, height: 5 },
    shadowRadius: 0,
    shadowOpacity: 1,
    elevation: 5,
    overflow: 'hidden',
    position: 'relative',
    gap: spacing.sm,
  },
  insightDecCircle: {
    position: 'absolute',
    width: 80,
    height: 80,
    borderRadius: 4,
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.07)',
    top: -24,
    right: -16,
    transform: [{ rotate: '8deg' }],
  },
  insightDecRect: {
    position: 'absolute',
    width: 40,
    height: 40,
    borderRadius: 4,
    backgroundColor: 'rgba(255,214,0,0.08)',
    bottom: -12,
    left: 28,
    transform: [{ rotate: '20deg' }],
  },
  insightHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    zIndex: 1,
  },
  insightIconWrap: {
    width: 30,
    height: 30,
    borderRadius: 4,
    backgroundColor: colors.yellow,
    borderWidth: 2,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  insightIcon: { fontSize: 14 },
  insightLabel: {
    fontSize: 10,
    fontWeight: '900',
    color: 'rgba(255,255,255,0.55)',
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  insightText: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.textInverse,
    lineHeight: 22,
    zIndex: 1,
  },

  // ── Action row ─────────────────────────────────────────────────────
  actionRow: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  actionBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
    borderWidth: 2.5,
    borderColor: colors.border,
    borderRadius: 6,
    backgroundColor: colors.bgElevated,
    paddingVertical: spacing.sm,
    shadowColor: colors.shadow,
    shadowOffset: { width: 3, height: 3 },
    shadowRadius: 0,
    shadowOpacity: 1,
    elevation: 3,
  },
  actionBtnDetail: {
    backgroundColor: colors.primaryLight,
  },
  actionBtnGraph: {
    backgroundColor: '#DCCCF7',
  },
  actionBtnPressed: {
    transform: [{ translateX: 3 }, { translateY: 3 }],
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0,
    elevation: 0,
  },
  actionBtnIcon: { fontSize: 14 },
  actionBtnText: {
    fontSize: 11,
    fontWeight: '900',
    color: colors.text,
    letterSpacing: 0.5,
  },
});
